name: Main

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    permissions:
      contents: read
    strategy:
      matrix:
        images: [eq-k8s-helm-deploy-image, eq-terraform-deploy-image, eq-python-deploy-image, eq-tinyproxy-image]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: >
          docker build -t onsdigital/${{ matrix.images }}:latest -f ${{ matrix.images }}/Dockerfile .
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [latest]"
          docker push onsdigital/${{ matrix.images }}:latest
