name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build-push:
    strategy:
      matrix:
        images: [eq-k8s-helm-deploy-image, eq-terraform-deploy-image, eq-python-deploy-image, eq-tinyproxy-image]
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 #v2.1.8
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set Tag and SHA
        run: |
          CLEAN_TAG=$(echo "${{ github.event.pull_request.head.ref }}" | tr / -)
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: Build
        run: >
          docker build -t onsdigital/${{ matrix.images }}:$TAG
          -t ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/${{ matrix.images }}:$TAG -f ${{ matrix.images }}/Dockerfile .
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing to DockerHub with tag $TAG"
          docker push onsdigital/${{ matrix.images }}:$TAG
      - name: Push to GAR
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}
          echo "Pushing to GAR with tag $TAG"
          docker push ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/${{ matrix.images }}:$TAG

